# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('movieid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
