# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_expect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='movieid',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
