# Generated by Django 3.1.7 on 2021-05-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20210424_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movielenid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtubeid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
