# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='search',
            name='id',
        ),
        migrations.AlterField(
            model_name='popularity',
            name='movieid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='search',
            name='word',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
