# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20170425_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
