# Generated by Django 3.1.7 on 2021-04-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
    ]
