# Generated by Django 3.1.7 on 2021-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210403_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='image/avatar.png', upload_to='image/'),
        ),
    ]
