# Generated by Django 3.1.7 on 2021-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(),
        ),
    ]
