# Generated by Django 3.1.7 on 2021-05-13 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210513_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
