# Generated by Django 3.1.7 on 2021-05-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
